# Generated by Django 2.0.6 on 2019-07-07 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=50, null=True)),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_todo_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
